CREATE TABLE shelf(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE book(
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    author VARCHAR(150) NOT NULL,
    current_page NUMERIC NOT NULL,
    shelf_id BIGINT NOT NULL REFERENCES shelf(id)
    );

CREATE TABLE comment(
    id BIGSERIAL PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book(id),
    content VARCHAR(500) NOT NULL
    );